name: CD

on:
    push:
        branches:
            - dev
            - main

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Set up Docker
              uses: docker/setup-buildx-action@v3

            - name: Log in to DockerHub
              run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

            - name: Create .env.docker
              run: |
                  echo "${{ secrets.ENV_DOCKER }}" > .env.docker

            - name: SSH to EC2 and Deploy
              uses: appleboy/ssh-action@v1.0.0
              with:
                  host: ${{ secrets.EC2_HOST }}
                  username: ${{ secrets.EC2_USER }}
                  key: ${{ secrets.EC2_SSH_KEY }}
                  script: |
                      cd /home/ubuntu/fitpull-be
                      git pull origin main
                      echo "${{ secrets.ENV_DOCKER }}" > .env.docker
                      docker-compose -f docker-compose.prod.yml up -d --build
